spring:
  application:
    name: com.xing.example
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: ocean

server:
  port: 60888

logging:
  config: classpath:conf/log4j2.xml

